# services:
#   postgres-db:
#     image: postgres
#     container_name: postgres-db
#     environment:
#       POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
#       POSTGRES_USER: ${POSTGRES_USER}
#       POSTGRES_DB: ${POSTGRES_DB}
#     ports:
#       - "5432:5432"
#     volumes:
#       - postgres-data:/var/lib/postgresql/data
#     healthcheck:
#       test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} || exit 1"]
#       interval: 10s
#       timeout: 5s
#       retries: 5
#     restart: unless-stopped

# volumes:
#   postgres-data:


networks:
  app-network:
    driver: bridge
services:
  pokedex-db:
    image: postgres
    volumes:
      - ./docker_ressources/init.sql:/docker-entrypoint-initdb.d/init.sql
      - pg_pokedex_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 1s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      # Use the Docker service DNS name and container port for DB connectivity inside the network
      POSTGRES_CONNECTION_STRING: "Host=pokedex-db;Port=5432;Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD};Database=${POSTGRES_DB}"
      # JWT settings for the API (keep secret out of the image; provide via .env)
      JWT__secret: "${JWT__secret}"
      # Optional: enable Swagger UI even outside Development
      Swagger__Enabled: "true"
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:8080/health || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 5
    depends_on:
      pokedex-db:
        condition: service_healthy
    networks:
      - app-network


volumes:
  pg_pokedex_data: