global:
  scrape_interval: 15s  # Frequency of metric scraping

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'API'
    static_configs:
      - targets: ['api:8080']
  - job_name: 'PSQL'
    static_configs:
      - targets: ['pokedex-db:5432']
