CREATE TABLE "species" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "pokedex_number" int,
  "name_fr" varchar(100),
  "name_en" varchar(100),
  "generation" int,
  "region" varchar(50)
);

CREATE TABLE "media" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "sprite_url" text,
  "artwork_url" text,
  "note" text
);

CREATE TABLE "pokemon" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "species_id" int,
  "form" varchar(50),
  "height" double,
  "weight" double,
  "base_experience" int,
  "image_id" int
);

CREATE TABLE "types" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(50),
  "description" text
);

CREATE TABLE "pokemon_types" (
  "pokemon_id" int,
  "type_id" int,
  PRIMARY KEY ("pokemon_id", "type_id")
);

CREATE TABLE "abilities" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(100),
  "description" text
);

CREATE TABLE "pokemon_abilities" (
  "pokemon_id" int,
  "ability_id" int,
  "is_hidden" boolean,
  PRIMARY KEY ("pokemon_id", "ability_id")
);

CREATE TABLE "moves" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(150),
  "description" text,
  "type_id" int,
  "power" int,
  "accuracy" double,
  "pp" int,
  "category" varchar(50)
);

CREATE TABLE "stats" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "pokemon_id" int,
  "hp" int,
  "attack" int,
  "defense" int,
  "special_attack" int,
  "special_defense" int,
  "speed" int
);

CREATE TABLE "evolutions" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "from_pokemon_id" int,
  "to_pokemon_id" int,
  "condition" text
);

CREATE TABLE "teams" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(150),
  "description" text,
  "owner" varchar(100)
);

CREATE TABLE "team_pokemons" (
  "team_id" int,
  "pokemon_id" int,
  "slot" int,
  PRIMARY KEY ("team_id", "pokemon_id")
);

ALTER TABLE "pokemon" ADD FOREIGN KEY ("species_id") REFERENCES "species" ("id");

ALTER TABLE "pokemon" ADD FOREIGN KEY ("image_id") REFERENCES "media" ("id");

ALTER TABLE "pokemon_types" ADD FOREIGN KEY ("pokemon_id") REFERENCES "pokemon" ("id");

ALTER TABLE "pokemon_types" ADD FOREIGN KEY ("type_id") REFERENCES "types" ("id");

ALTER TABLE "pokemon_abilities" ADD FOREIGN KEY ("pokemon_id") REFERENCES "pokemon" ("id");

ALTER TABLE "pokemon_abilities" ADD FOREIGN KEY ("ability_id") REFERENCES "abilities" ("id");

ALTER TABLE "moves" ADD FOREIGN KEY ("type_id") REFERENCES "types" ("id");

ALTER TABLE "stats" ADD FOREIGN KEY ("pokemon_id") REFERENCES "pokemon" ("id");

ALTER TABLE "evolutions" ADD FOREIGN KEY ("from_pokemon_id") REFERENCES "pokemon" ("id");

ALTER TABLE "evolutions" ADD FOREIGN KEY ("to_pokemon_id") REFERENCES "pokemon" ("id");

ALTER TABLE "team_pokemons" ADD FOREIGN KEY ("team_id") REFERENCES "teams" ("id");

ALTER TABLE "team_pokemons" ADD FOREIGN KEY ("pokemon_id") REFERENCES "pokemon" ("id");
